#!/bin/bash

# Get the users sudo password
sudo -v

# Move .wezterm.lua to Windows home on wsl
if [ "$(uname -r | sed -n 's/.*\( *Microsoft *\).*/\1/ip')" ]; then
  WIN_HOME="/mnt/c/Users/$(whoami)"
  if [ -d "$WIN_HOME" ]; then
    cp "$HOME/.wezterm.lua" "$WIN_HOME/.wezterm.lua"
  fi
fi

/bin/bash "$HOME"/.config/yadm/packages.sh

# Initialise nvim
nvim --headless -c "Lazy sync"

# Set git config
git config --global advice.addIgnoredFile false
git config --global commit.template "$HOME"/.gitmessage
git config --global user.name "Kai Chevannes"
git config --global core.editor "nvim"

# Set up ssh key
if [ ! -f ~/.ssh/id_ed25519 ]; then
  ssh-keygen -t ed25519 -N "" -f ~/.ssh/id_ed25519
  eval "$(ssh-agent -s)"
  ssh-add ~/.ssh/id_ed25519
fi

# Show ssh key
echo -e "\n\033[34mCopying generated SSH key to clipboard.\033[0m"
cat ~/.ssh/id_ed25519.pub | tee /dev/tty | xclip -selection clipboard
echo -e "\n\033[34mTo finish setup, run: git config --global user.email \"your_email@example.com\"\033[0m"
